### ISSUE TITLE
Felmeddelande när man följt instruktionen

### ISSUE THREAD

**Issue by Hawkwing73** [easitab/EasitGoWebservice#1]
Har följt instruktionen för att installera modulen i Powershell.
Får felmeddelande enligt skärmdump när jag försöker "show details"
![bild](https://user-images.githubusercontent.com/57670134/68855197-08e5b680-06de-11ea-9aee-8ba7f4546cb8.png)

**Comment by easitab** [comment]
Created ticket 229930 with Easit.
