### ISSUE TITLE
Unable to get item when using parameter ColumnFilter with Get-GOItems

### ISSUE THREAD

**Issue by easitanth** [easitab/EasitGoWebservice#5]
Executing the following command:
Get-GOItems -url $url -apikey $api -view Contacts_v1 -page 1 -ColumnFilter 'Id,EQUALS,1'

Get the following error:
Get-GOItems : Failed to connect to BPS!
At line:1 char:12
 $result2 = Get-GOItems -url $url -apikey $api -view Contacts_v1 -pag ...
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
     FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-GOItems

Get-GOItems : Server Error
500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed.
At line:1 char:12
 $result2 = Get-GOItems -url $url -apikey $api -view Contacts_v1 -pag ...
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
     FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-GOItems

**Comment by easitab** [comment]
Solved in commit e4af574ce16da55c0546a7cc753b1fa1893efe9c
